<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Admin Kamus')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>

    <!--Navbar layout-->
<nav class="navbar navbar-inverse navbar-fixed-top">
      
      <div class="container"><!--container-->  
        <div class="navbar-header"><!--navbar-header-->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
          <a class="navbar-brand" href="<?php echo $this->url('admin') ?>">ADMINISTRATOR</a>
        </div><!--navbar-header-->
        
        <!--Navbar Left-->
        <ul class="nav navbar-nav navbar-left">
                <li class="active"><a href="<?php echo $this->url('admin') ?>">Home</a></li>
                <li><a href="<?php echo $this->url('admin/istilah') ?>">Istilah</a></li>
                <li><a href="<?php echo $this->url('admin/komentar') ?>">Komentar</a></li>
        </ul>
        <!--Navbar Left-->

        <!--Navbar Right-->
        <ul class="nav navbar-nav navbar-right">
                <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <span class="glyphicon glyphicon-user"></span> Hallo,
                <?php
                echo $_SESSION['username'];
                ?>
                <b class="caret"></b></a>
             
            <ul class="dropdown-menu">
            <li><a href="#" data-toggle="modal" data-target="#profil"><span class="glyphicon glyphicon-user"></span> Profil</a></li>
                
            <li class="divider"></li>
            <li><a href="<?php echo $this->url('zfcuser/logout') ?>" onclick="return confirm('Apakah anda akan keluar?');"><span class="glyphicon glyphicon-off"></span> Keluar</a></li>
            </ul>
            </li>
        </ul><!--Navbar Right-->
    </div><!--container-->
</nav><!--Navbar layout-->



   
       <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Ramadhansyah Tanjung. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
       
        <?php echo $this->inlineScript() ?>
    </body>
</html>
