<form method="post" action="&#x2F;user&#x2F;login" autocomplete="off">
    <dl class="zend_form">
        
        <dt><label for="identity">Email</label></dt>
        <dd><input name="identity" type="text" value=""></dd>

        <dt><label for="credential">Password</label></dt>
        <dd><input type="password" name="credential" value=""></dd>

        
        <dd><button type="submit" name="submit" value="">Sign In</button></dd>
    </dl>

</form>
Not registered? <a href="/user/register">Sign up!</a>
            <hr>
            <footer>
                <p>&copy; 2005 - 2016 by Zend Technologies Ltd. All rights reserved.</p>
            </footer>