
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
</head>
<link rel="stylesheet" href="/css/admin-login.css" type="text/css" media="screen, projection">
<body>
    
<div class="signin-form">

    <div class="container">
     
        
       <form class="form-signin" method="post" id="login-form">
      
        <h2 class="form-signin-heading">Log In to WebApp.</h2><hr />
        
        <div id="error">
        <!-- error will be shown here ! -->
        </div>
        
        <div class="form-group">
        <input type="email" class="form-control" placeholder="Email address" name="user_email" id="user_email" />
        <span id="check-e"></span>
        </div>
        
        <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" name="password" id="password" />
        </div>
       
        <hr />
        
        <div class="form-group">
            <button type="submit" class="btn btn-default" name="btn-login" id="btn-login">
            <span class="glyphicon glyphicon-log-in"></span> &nbsp; Sign In
            </button> 
        </div>  
      
      </form>

    </div>
    
</div>
    
<script src="bootstrap/js/bootstrap.min.js"></script>

</body>
</html><form method="post" action="&#x2F;user&#x2F;login" autocomplete="off">
    <dl class="zend_form">
        
        <dt><label for="identity">Email</label></dt>
        <dd><input name="identity" type="text" value=""></dd>

        <dt><label for="credential">Password</label></dt>
        <dd><input type="password" name="credential" value=""></dd>

        
        <dd><button type="submit" name="submit" value="">Sign In</button></dd>
    </dl>

</form>
Not registered? <a href="/user/register">Sign up!</a>
            <hr>
            <footer>
                <p>&copy; 2005 - 2016 by Zend Technologies Ltd. All rights reserved.</p>
            </footer>