<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('::(KASTI)::')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <style type="text/css">
        * {
            margin:0px;
            padding:0px;
        }
        .form-group input[type="text"],
        .form-group input['textarea'] {
        font-size: 10px;
        margin:0px;
        padding:0px;

        }
        #abjad > a{
          margin-left: 5px;
          margin-right: 5px;
        }
        #abjad {
          margin-bottom: 0px;
        }
        #article{
          overflow: scroll;
          height: 612px;
          width: 750px;
        }
        #istilah-terbaru > .col-md-4 {
          margin-right: 20px;
          width: 450px;
        }


        </style>
    </head>
    <body>
      
       <nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">KAMUS ISTILAH TEKNOLOGI INFORMASI (KASTI)</a>
        </div>
      
</nav><!--Navbar layout-->

<div class="container">
         <div class="row">
  


  <div class="col-md-8" name="center">
    <div class="panel panel-default">
  <div class="panel-heading"><!--heading-->

  <form class="form-inline">
  <div class="form-group">
  <input type="text" class="form-control" id="search" size="90" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-search"></span> Search</button>
  </form>
  </div><!--heading-->
  
  <div id="abjad" class="panel-body"><!--body-->
    <a href="">0-9</a>
    <a href="">A</a>
    <a href="">B</a>
    <a href="">C</a>
    <a href="">D</a>
    <a href="">E</a>
    <a href="">F</a>
    <a href="">G</a>
    <a href="">H</a>
    <a href="">I</a>
    <a href="">J</a>
    <a href="">K</a>
    <a href="">L</a>
    <a href="">M</a>
    <a href="">N</a>
    <a href="">O</a>
    <a href="">P</a>
    <a href="">Q</a>
    <a href="">R</a>
    <a href="">S</a>
    <a href="">T</a>
    <a href="">U</a>
    <a href="">V</a>
    <a href="">W</a>
    <a href="">X</a>
    <a href="">Y</a>
    <a href="">Z</a>
  </div><!--body-->
</div>
<div id="article">
  
</div>
  <div class="panel panel-success">
  <div class="panel-heading"><span class="glyphicon glyphicon-home"></span> Jumlah Istilah</div>
  <div class="panel-body">
  <p align="center">Jumlah istilah </p>
  <p align="center"> 12.580 </p>

  </div>
</div>



      </div>

      <div id="istilah-terbaru" class="col-md-4">
      <div  class="list-group">
  <a href="#" class="list-group-item active">
    <span class="glyphicon glyphicon-star"> Istilah Terbaru</span>
  </a>
  <a href="#" class="list-group-item">Istilah-1</a>
  <a href="#" class="list-group-item">Istilah-2</a>
  <a href="#" class="list-group-item">Istilah-3</a>
  <a href="#" class="list-group-item">Istilah-4</a>
  <a href="#" class="list-group-item">Istilah-5</a>
</div>

 <div  class="list-group danger">
  <a href="#" class="list-group-item active">
    <span class="glyphicon glyphicon-star"> Istilah Terpopuler</span>
  </a>
  <a href="#" class="list-group-item">Istilah</a>
  <a href="#" class="list-group-item">Istilah</a>
  <a href="#" class="list-group-item">Istilah</a>
  <a href="#" class="list-group-item">Istilah</a>
  <a href="#" class="list-group-item">Istilah</a>
</div>


<div class="panel panel-info">
  <div class="panel-heading"><span class="glyphicon glyphicon-pencil"></span> KOMENTAR</div>
  <div class="panel-body">

<form class="form-horizontal">

 <input type="hidden" name="id" value="">
  <table class="table table-bordered table-hover table-striped tablesorter" align="center">
            <tr>
            <td>
  <textarea class="form-control" name="komentar" rows="8" placeholder="Isi Komentar Anda di sini tentang Website ini"></textarea>
</td>
            </tr>

            <tr>
            <td colspan="2" align="right"><button type="submit" class="btn btn-md btn-warning" name="tambah"><b>Kirim </b><i class="fa fa-arrow-circle-right"></i></button></td>
            </tr>

</table>
</form>


  </div>
</div>





 

      </div>



 
</div>
 <div class="col-md-8">
      

    </div>

</div>



</div>

         
        <div class="container">
            <?php echo $this->content; ?>
            <hr>

            <footer>
                <p align="center">&copy; 2005 - <?php echo date('Y') ?> by Ramadhansyah Tanjung     <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
