<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="/js/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css">
	<script type="text/javascript">
		$(document).ready(function(){
			$("#datepicker").datepicker();
		});
	</script>
</head>
<body>
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  </ul>

  	<form  action="aksi-tambah-buku.php" method="POST" enctype="multipart/form-data">
						
						<table class="table table-bordered table-hover table-striped tablesorter" align="center">
						<tr>
						<td>Id</td>
						<td><input type="text" name="kode_buku" size="160" placeholder="Id istilah . . ."required autocomplete="off"></td>
						</tr>
						
						<tr>
						<td>Istilah</td>
						<td><input type="text" name="judul_buku" size="160" placeholder="isikan Istilah . . ." required autocomplete="off"></td>
						</tr>
						
						<tr>
						<td>Konteks</td>
						<td><input type="tex" name="arti" id="arti" size="110" placeholder="isikan harga-buku" required>
						<script type="text/javascript">CKEDITOR.replace('arti');</script></td>
						</tr>
						
						<tr>
						<td>Tanggal</td>
						<td><input type="text"></input></td>
						</tr>
						
						<tr>
						<td>HIT</td>
						<td><input type="text" name="keterangan" size="160" placeholder="Keterangan tentang Buku" required></td>
						</tr>
						
						<tr>
						<td colspan="2" align="right"><button type="submit" class="btn btn-md btn-warning" name="tambah"><b>Tambah Istilah </b><i class="fa fa-arrow-circle-right"></i></button></td>
						</tr>

						
						</table>
						</form>



</body>
</html>