<!DOCTYPE html>
<html>
<head>
	<title></title>
	
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/css/dataTables.bootstrap.css">
	
</head>
<body>

	<div class="container">
	<div class="box-body table-responsive">
		<table id="data" class="table table-striped table-bordered table-hover">
			<thead>
				<tr>			
					<th>NO</th>
					<th>ID</th>
					<th>Istilah</th>
					<th>Konteks</th>
					<th>Hit</th>
				</tr>
			</thead>
			<tbody>
			<?php $no=0; ?>
                <?php foreach ($this->istilah as $istilah): ?>


				<tr>				
					<td><?php echo ++$no ?></td>
					<td><?php echo $istilah->id ?></td>
					<td><?php echo $this->escapeHtml($istilah->istilah) ?></td>
					<td></td>
					<td><?php echo $istilah->hit ?></td>
					
				</tr>
			    <?php endforeach ?>
			</tbody>
		</table>
		</div>
	</div>
<script type="text/javascript" src=/js/jquery-1.11.1.min.js></script>
<script type="text/javascript" src=/js/bootstrap.min.js></script>
<script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
<script src="/js/dataTables.bootstrap.js"></script>	
<script type="text/javascript">
	$(function(){
		$('#data').DataTable();
	});

	</script>
</body>
</html>